# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Election 2014
tagline:          Waterloo Region
description:      'Maintained by <a href="http://waterlooregion.org">Social Planning Council of Kitchener-Waterloo</a>'
url:              http://info.waterlooregion.org/election-2014
baseurl:          '/election-2014'
paginate:         5

author:
  name:           'Todd Turnbull'
  url:            http://info.waterlooregion.org

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/info-waterloo-region/election-2014
