# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Waterloo Region Election 2014
tagline:          'Candidates'
description:      'Maintained by <a href="http://waterlooregion.org">Social Planning Council of Kitchener-Waterloo</a>'
url:              http://info-waterloo-region.github.io/election-2014
baseurl:          '/election-2014'
paginate:         5

author:
  name:           'Todd Turnbull'
  url:            http://waterlooregion.org

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/info-waterloo-region/election-2014
