# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Election 2014'
description:      'October 27'
tagline:          'October 27' 
url:              http://info.waterlooregion.org/election-2014
baseurl:          '/election-2014'

author:
  name:           'Todd Turnbull'
  url:            http://info.waterlooregion.org
  email:          info@waterlooregion.org

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/info-waterloo-region/election-2014
